# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adotop < Formula
  desc "Terminal UI for Azure DevOps pull requests"
  homepage "https://github.com/superyyrrzz/adotop"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superyyrrzz/adotop/releases/download/v0.1.1/adotop_0.1.1_darwin_x86_64.tar.gz"
      sha256 "4bbf1ba8cb989a52d082f7d86385492fc6d53a19f71be9fab6cbfc8bfcc5f5df"

      define_method(:install) do
        bin.install "adotop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superyyrrzz/adotop/releases/download/v0.1.1/adotop_0.1.1_darwin_arm64.tar.gz"
      sha256 "abd200e407d163282ee173e241a18a70e9961fa06c6882600a254ee1cb859efe"

      define_method(:install) do
        bin.install "adotop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/superyyrrzz/adotop/releases/download/v0.1.1/adotop_0.1.1_linux_x86_64.tar.gz"
      sha256 "c4ef2b03812f55e407b219859118ebbe3ab5e36e2ff4e1e2e01170854592df4a"
      define_method(:install) do
        bin.install "adotop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superyyrrzz/adotop/releases/download/v0.1.1/adotop_0.1.1_linux_arm64.tar.gz"
      sha256 "4d21faa2be278172fa354818b58103b098dc8546b9a33ea9fb840be51ae54d25"
      define_method(:install) do
        bin.install "adotop"
      end
    end
  end

  test do
    system "#{bin}/adotop --version"
  end
end
